export const LOAD_STACKS_SUCCESS = 'LOAD_STACKS_SUCCESS';
export const CREATE_STACK_SUCCESS = 'CREATE_STACK_SUCCESS';
export const REMOVE_STACK_SUCCESS = 'REMOVE_STACK_SUCCESS';

export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
